CREATE TABLE IF NOT EXISTS animal (
  id SERIAL PRIMARY KEY UNIQUE,
  name VARCHAR (50),
  type VARCHAR (50) NOT NULL,
  breed VARCHAR (50) NOT NULL,
  cost DOUBLE PRECISION NOT NULL,
  charact VARCHAR (50) NOT NULL,
  birthDate TIMESTAMP NOT NULL,
  secretInformation VARCHAR (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS animal_type (
  id SERIAL PRIMARY KEY UNIQUE,
  type VARCHAR (50) UNIQUE
);
