<#-- @ftlvariable name="currentUser" type="Model.User" -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Home page</title>
</head>
<body>
<nav role="navigation">
    <ul>
        <li><a href="/login">Log in</a></li>
        <li><a href="/hello">Say hello</a></li>
        <li><a href="/admin">Only for admin page</a></li>
        <li><a href="/logout">Log out</a></li>
    </ul>
</nav>
</body>
</html>